### ISSUE TITLE
Docker rake task fails

### ISSUE THREAD

**Issue by mchelen** [DCAFEngineering/dcaf_case_management#1260]
* **What are we trying to do?**
Run DCAF with Docker

* **What feature or behavior is this required for?**
Docker development

* ** Error: **
```
$ docker-compose run web rake db:seed
Creating dcafcasemanagement_db_1 ...
Creating dcafcasemanagement_db_1 ... done
rake aborted!
Mongo::Error::NoServerAvailable: No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47221982700100 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015
/usr/local/bundle/gems/mongo-2.4.3/lib/mongo/server_selector/selectable.rb:115:in `select_server'
/usr/local/bundle/gems/mongo-2.4.3/lib/mongo/collection/view/readable.rb:138:in `block in count'
/usr/local/bundle/gems/mongo-2.4.3/lib/mongo/retryable.rb:43:in `read_with_retry'
/usr/local/bundle/gems/mongo-2.4.3/lib/mongo/collection/view/readable.rb:137:in `count'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:71:in `block in count'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:522:in `try_cache'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:71:in `count'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/contextual.rb:20:in `count'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/persistable/destroyable.rb:53:in `destroy_all'
/usr/src/app/db/seeds.rb:10:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:287:in `load'
/usr/local/bundle/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:287:in `block in load'
/usr/local/bundle/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.5/lib/active_support/dependencies.rb:287:in `load'
/usr/local/bundle/gems/mongoid-6.1.0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)   
```

**Comment by mchelen** [comment]
Maybe caused by ec61c1b55b7 but we also need 62dd4304fe9efc

**Comment by ChrisBarthol** [comment]
I tried to install this project and ran into the same issue.

Can confirm it is from the ec61c1b55b764dd9b2b7955e217da46283775c2c as I switched back to the environment variables and was able to run `docker-compose run web rake db:seed` successfully.

**Comment by colinxfleming** [comment]
durf. sorry folks. If @mchelen or @ChrisBarthol want to roll out a fix that'd be clutch (probably just reverting the changes in lines 4-6 and 12-14?)  but otherwise I'll try and spin one up shortly.
