### ISSUE TITLE
Flakey Call Log Test

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1615]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make out test suite stronger by fixing a flakey test.

* **How could we solve this issue? (Not knowing is okay!)**

Dunno!

* **Anything else?**

Error:

```
..................................................................................................................    HTML screenshot: /home/circleci/abortioneering/tmp/capybara/screenshot_2019-02-20-12-30-05.978.html
    Image screenshot: /home/circleci/abortioneering/tmp/capybara/screenshot_2019-02-20-12-30-05.978.png
[Screenshot]: tmp/screenshots/failures_test_0001_should log a phone call into the activity log.png
E

Error:
EventLogInteractionTest::logging phone calls#test_0001_should log a phone call into the activity log:
Selenium::WebDriver::Error::UnknownError: unknown error: Element <a href="#" data-toggle="dropdown" class="dropdown-toggle">...</a> is not clickable at point (1250, 25). Other element would receive the click: <div class="modal fade new-call in" tabindex="-1" role="dialog" id="123-123-1234" style="display: block; padding-right: 15px;">...</div>
  (Session info: chrome=72.0.3626.81)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-141-generic x86_64)
    test/integration_helper.rb:51:in `sign_out'
    test/integration_helper.rb:56:in `log_out'
    test/system/event_log_interaction_test.rb:25:in `block (2 levels) in <class:EventLogInteractionTest>'


bin/rails test test/system/event_log_interaction_test.rb:18

......................................
```

Maybe the same issue failing in another way here:

```
.............Attempt to select disabled option: 5c6dc97947ab5e00c73bb20d
.................................................................................    HTML screenshot: /home/circleci/abortioneering/tmp/capybara/screenshot_2019-02-20-21-42-01.485.html
    Image screenshot: /home/circleci/abortioneering/tmp/capybara/screenshot_2019-02-20-21-42-01.485.png
[Screenshot]: tmp/screenshots/failures_test_0001_should log a phone call into the activity log.png
F

Failure:
ActivityLogTest::logging phone calls#test_0001_should log a phone call into the activity log [/home/circleci/abortioneering/test/system/activity_log_test.rb:33]:
Expected false to be truthy.


bin/rails test test/system/activity_log_test.rb:18

..Attempt to select disabled option: 5c6dc9aa47ab5e00c73bb652
.....................................................................................
```

![screenshot_2019-02-20-21-42-01 485](https://user-images.githubusercontent.com/6129479/53127480-8ce48680-3530-11e9-85ec-33f0489fc98a.png)

**Comment by colinxfleming** [comment]
This has not been super problematic recently so I'm closing. Can always reopen if it winds up continuing to bite.
