### ISSUE TITLE
Failing integration test

### ISSUE THREAD

**Issue by zorkian** [DCAFEngineering/dcaf_case_management#903]
* **What are we trying to do?**

Submit documentation update, and get the integration tests to pass. Looks like `test/integration/pledge_fulfillment_test.rb` has a failing test: `test_0002_should show a link to the pledge fulfillment tab after pledge sent - PledgeFulfillmentTest::visiting the edit patient view as a data volunteer`.

* **What feature or behavior is this required for?**

Onboarding and submitting PRs etc.

* **How could we solve this issue? (Not knowing is okay!)**

Make the test pass.

* **Anything else?**

Not this second!

**Comment by zorkian** [comment]
Link to a failure: https://circleci.com/gh/colinxfleming/dcaf_case_management/1731?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by zorkian** [comment]
Failing output:

```
Expected false to be truthy.
test/integration/pledge_fulfillment_test.rb:90:in `block (2 levels) in <class:PledgeFulfillmentTest>'
```

**Comment by lilliealbert** [comment]
I got one locally, but when I rerun with the same seed, I get a different failure 👻  :sob:


### failure No 1:
```
lillie@lemur-8 dcaf_case_management (master) $ rake
Started with run options --seed 23038

    HTML screenshot: /Users/lillie/projects/dcaf_case_management/tmp/capybara/screenshot_2017-03-04-11-05-34.178.htmlETA: 00:02:07
    Image screenshot: /Users/lillie/projects/dcaf_case_management/tmp/capybara/screenshot_2017-03-04-11-05-34.178.png
 FAIL["test_0001_should let you mark a pledge submitted", #<Class:0x007feb0d5b0888>, 102.41897805500776]
 test_0001_should let you mark a pledge submitted#SubmitPledgeTest::submitting a pledge (102.42s)
        Expected false to be truthy.
        test/integration/submit_pledge_test.rb:37:in `block (2 levels) in <class:SubmitPledgeTest>'

58bb105df47575191fbc7f51,58bb105df47575191fbc7f56,58bb105df47575191fbc7f4c,58bb105df47575191fbc7f47 Time: 00:03:16,  ETA: 00:00:08
  328/328: [=================================================================================] 100% Time: 00:03:23, Time: 00:03:23

Finished in 203.84374s
328 tests, 692 assertions, 1 failures, 0 errors, 0 skips
```

### failure No 2:
```
lillie@lemur-8 dcaf_case_management (add-referred-to-clinic-to-pregnancy) $ rake TESTOPTS="--seed 23038"
Started with run options --seed 23038

    HTML screenshot: /Users/lillie/projects/dcaf_case_management/tmp/capybara/screenshot_2017-03-04-12-02-25.381.htmlETA: 00:00:32
    Image screenshot: /Users/lillie/projects/dcaf_case_management/tmp/capybara/screenshot_2017-03-04-12-02-25.381.png
ERROR["test_0001_should be able to create user", #<Class:0x007ff2f0e7e538>, 176.19960451102816]
 test_0001_should be able to create user#CreateUserTest::admin user (176.20s)
MockExpectationError:         MockExpectationError: expected deliver_now() => nil
            test/integration/create_user_test.rb:43:in `block (3 levels) in <class:CreateUserTest>'
            test/integration/create_user_test.rb:29:in `block (2 levels) in <class:CreateUserTest>'

58bb1d68f475751bfbf782e4,58bb1d68f475751bfbf782e9,58bb1d68f475751bfbf782df,58bb1d68f475751bfbf782da Time: 00:03:18,  ETA: 00:00:08
  328/328: [=================================================================================] 100% Time: 00:03:25, Time: 00:03:25

Finished in 205.08693s
328 tests, 689 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by rivers** [comment]
Another failure: https://circleci.com/gh/colinxfleming/dcaf_case_management/1752

```
test_0001_should add a call to completed when a call was made within 8 hrs - CallListTest::completed calls section

Expected false to be truthy.
test/integration/call_list_test.rb:78:in `block (3 levels) in <class:CallListTest>'
test/integration/call_list_test.rb:77:in `block (2 levels) in <class:CallListTest>'
```

**Comment by colinxfleming** [comment]
I think these are largely resolved in our migration to ~ the new hotness ~, SystemTest. Should spin up new issues if we start to see failures again. 

(miss u, CA hackathon team! <3 )
